'use strict';

const CDN = (n) => `https://cdn2.csgo.com/item/image/width=155/${encodeURIComponent(n)}.png`;

const SKINS = [
  {id:1,  name:'Karambit | Fade (Factory New)',             weapon:'Керамбит',    rarity:'knife',      price:315000, img:CDN('★ Karambit | Fade (Factory New)')},
  {id:2,  name:'Butterfly Knife | Doppler (Factory New)',   weapon:'Нож-бабочка', rarity:'knife',      price:580000, img:CDN('★ Butterfly Knife | Doppler (Factory New)')},
  {id:3,  name:'M9 Bayonet | Crimson Web (Field-Tested)',   weapon:'Нож M9',      rarity:'knife',      price:47000,  img:CDN('★ M9 Bayonet | Crimson Web (Field-Tested)')},
  {id:4,  name:'Bayonet | Fade (Factory New)',              weapon:'Штык-нож',    rarity:'knife',      price:39000,  img:CDN('★ Bayonet | Fade (Factory New)')},
  {id:5,  name:'Karambit | Doppler (Factory New)',          weapon:'Керамбит',    rarity:'knife',      price:95000,  img:CDN('★ Karambit | Doppler (Factory New)')},
  {id:6,  name:'M9 Bayonet | Doppler (Factory New)',        weapon:'Нож M9',      rarity:'knife',      price:420000, img:CDN('★ M9 Bayonet | Doppler (Factory New)')},
  {id:7,  name:'Butterfly Knife | Fade (Factory New)',      weapon:'Нож-бабочка', rarity:'knife',      price:248000, img:CDN('★ Butterfly Knife | Fade (Factory New)')},
  {id:8,  name:'Falchion Knife | Fade (Factory New)',       weapon:'Нож-фальшион',rarity:'knife',      price:28000,  img:CDN('★ Falchion Knife | Fade (Factory New)')},
  {id:9,  name:'Flip Knife | Doppler (Factory New)',        weapon:'Нож-флип',    rarity:'knife',      price:24000,  img:CDN('★ Flip Knife | Doppler (Factory New)')},
  {id:10, name:'Huntsman Knife | Fade (Factory New)',       weapon:'Нож охотника',rarity:'knife',      price:32000,  img:CDN('★ Huntsman Knife | Fade (Factory New)')},
  {id:11, name:'M4A4 | Howl (Field-Tested)',                weapon:'M4A4',        rarity:'contraband', price:185000, img:CDN('M4A4 | Howl (Field-Tested)')},
  {id:12, name:'AK-47 | Fire Serpent (Field-Tested)',       weapon:'AK-47',       rarity:'covert',     price:74000,  img:CDN('AK-47 | Fire Serpent (Field-Tested)')},
  {id:13, name:'AWP | Asiimov (Field-Tested)',              weapon:'AWP',         rarity:'covert',     price:10695,  img:CDN('AWP | Asiimov (Field-Tested)')},
  {id:14, name:'Desert Eagle | Blaze (Factory New)',        weapon:'Desert Eagle',rarity:'restricted', price:84150,  img:CDN('Desert Eagle | Blaze (Factory New)')},
  {id:15, name:'AK-47 | Vulcan (Field-Tested)',             weapon:'AK-47',       rarity:'covert',     price:17200,  img:CDN('AK-47 | Vulcan (Field-Tested)')},
  {id:16, name:'AWP | Medusa (Field-Tested)',               weapon:'AWP',         rarity:'covert',     price:196000, img:CDN('AWP | Medusa (Field-Tested)')},
  {id:17, name:'M4A4 | Asiimov (Field-Tested)',             weapon:'M4A4',        rarity:'covert',     price:12000,  img:CDN('M4A4 | Asiimov (Field-Tested)')},
  {id:18, name:'AK-47 | Fuel Injector (Field-Tested)',      weapon:'AK-47',       rarity:'covert',     price:16300,  img:CDN('AK-47 | Fuel Injector (Field-Tested)')},
  {id:19, name:'AWP | Fade (Factory New)',                  weapon:'AWP',         rarity:'covert',     price:91778,  img:CDN('AWP | Fade (Factory New)')},
  {id:20, name:'AWP | Printstream (Factory New)',           weapon:'AWP',         rarity:'covert',     price:30434,  img:CDN('AWP | Printstream (Factory New)')},
  {id:21, name:'AK-47 | Bloodsport (Field-Tested)',         weapon:'AK-47',       rarity:'covert',     price:13800,  img:CDN('AK-47 | Bloodsport (Field-Tested)')},
  {id:22, name:'AWP | Neo-Noir (Field-Tested)',             weapon:'AWP',         rarity:'covert',     price:3293,   img:CDN('AWP | Neo-Noir (Field-Tested)')},
  {id:23, name:'AWP | Lightning Strike (Factory New)',      weapon:'AWP',         rarity:'covert',     price:51739,  img:CDN('AWP | Lightning Strike (Factory New)')},
  {id:24, name:'AWP | Wildfire (Factory New)',              weapon:'AWP',         rarity:'covert',     price:18948,  img:CDN('AWP | Wildfire (Factory New)')},
  {id:25, name:'AK-47 | Neon Revolution (Field-Tested)',    weapon:'AK-47',       rarity:'covert',     price:9200,   img:CDN('AK-47 | Neon Revolution (Field-Tested)')},
  {id:26, name:'AK-47 | The Empress (Field-Tested)',        weapon:'AK-47',       rarity:'covert',     price:7199,   img:CDN('AK-47 | The Empress (Field-Tested)')},
  {id:27, name:'M4A1-S | Printstream (Factory New)',        weapon:'M4A1-S',      rarity:'covert',     price:58000,  img:CDN('M4A1-S | Printstream (Factory New)')},
  {id:28, name:'USP-S | Printstream (Factory New)',         weapon:'USP-S',       rarity:'covert',     price:30000,  img:CDN('USP-S | Printstream (Factory New)')},
  {id:29, name:'Desert Eagle | Printstream (Factory New)',  weapon:'Desert Eagle',rarity:'covert',     price:7331,   img:CDN('Desert Eagle | Printstream (Factory New)')},
  {id:30, name:'AWP | Wildfire (Field-Tested)',             weapon:'AWP',         rarity:'classified', price:4199,   img:CDN('AWP | Wildfire (Field-Tested)')},
  {id:31, name:'AK-47 | Nightwish (Field-Tested)',          weapon:'AK-47',       rarity:'covert',     price:5100,   img:CDN('AK-47 | Nightwish (Field-Tested)')},
  {id:32, name:'M4A1-S | Hyper Beast (Field-Tested)',       weapon:'M4A1-S',      rarity:'covert',     price:6900,   img:CDN('M4A1-S | Hyper Beast (Field-Tested)')},
  {id:33, name:'AK-47 | Redline (Field-Tested)',            weapon:'AK-47',       rarity:'classified', price:2840,   img:CDN('AK-47 | Redline (Field-Tested)')},
  {id:34, name:'AK-47 | Blue Laminate (Factory New)',       weapon:'AK-47',       rarity:'classified', price:1998,   img:CDN('AK-47 | Blue Laminate (Factory New)')},
  {id:35, name:'AWP | Chromatic Aberration (Field-Tested)', weapon:'AWP',         rarity:'covert',     price:2700,   img:CDN('AWP | Chromatic Aberration (Field-Tested)')},
  {id:36, name:'AWP | Electric Hive (Field-Tested)',        weapon:'AWP',         rarity:'classified', price:3509,   img:CDN('AWP | Electric Hive (Field-Tested)')},
  {id:37, name:'AK-47 | Head Shot (Field-Tested)',          weapon:'AK-47',       rarity:'covert',     price:2999,   img:CDN('AK-47 | Head Shot (Field-Tested)')},
  {id:38, name:'AK-47 | Neon Rider (Field-Tested)',         weapon:'AK-47',       rarity:'covert',     price:4660,   img:CDN('AK-47 | Neon Rider (Field-Tested)')},
  {id:39, name:'AK-47 | The Oligarch (Field-Tested)',       weapon:'AK-47',       rarity:'covert',     price:8400,   img:CDN('AK-47 | The Oligarch (Field-Tested)')},
  {id:40, name:'Desert Eagle | Code Red (Field-Tested)',    weapon:'Desert Eagle',rarity:'covert',     price:3419,   img:CDN('Desert Eagle | Code Red (Field-Tested)')},
  {id:41, name:'AWP | Crakow! (Field-Tested)',              weapon:'AWP',         rarity:'classified', price:3450,   img:CDN('AWP | Crakow! (Field-Tested)')},
  {id:42, name:'M4A1-S | Golden Coil (Field-Tested)',       weapon:'M4A1-S',      rarity:'classified', price:2800,   img:CDN('M4A1-S | Golden Coil (Field-Tested)')},
  {id:43, name:'AWP | Chrome Cannon (Field-Tested)',        weapon:'AWP',         rarity:'classified', price:2249,   img:CDN('AWP | Chrome Cannon (Field-Tested)')},
  {id:44, name:'Desert Eagle | Kumicho Dragon (Field-Tested)',weapon:'Desert Eagle',rarity:'classified',price:1800,  img:CDN('Desert Eagle | Kumicho Dragon (Field-Tested)')},
  {id:45, name:'Desert Eagle | Midnight Storm (Field-Tested)',weapon:'Desert Eagle',rarity:'classified',price:1949,  img:CDN('Desert Eagle | Midnight Storm (Field-Tested)')},
  {id:46, name:'P250 | Asiimov (Field-Tested)',             weapon:'P250',        rarity:'restricted', price:340,    img:CDN('P250 | Asiimov (Field-Tested)')},
  {id:47, name:'MP7 | Fade (Factory New)',                  weapon:'MP7',         rarity:'restricted', price:1150,   img:CDN('MP7 | Fade (Factory New)')},
  {id:48, name:'SSG 08 | Blood in the Water (Factory New)', weapon:'SSG 08',      rarity:'covert',     price:11000,  img:CDN('SSG 08 | Blood in the Water (Factory New)')},
  {id:49, name:'Glock-18 | Water Elemental (Factory New)',  weapon:'Glock-18',    rarity:'restricted', price:790,    img:CDN('Glock-18 | Water Elemental (Factory New)')},
  {id:50, name:'Desert Eagle | Mecha Industries (Field-Tested)',weapon:'Desert Eagle',rarity:'restricted',price:506, img:CDN('Desert Eagle | Mecha Industries (Field-Tested)')},
  {id:51, name:'MAC-10 | Neon Rider (Field-Tested)',        weapon:'MAC-10',      rarity:'restricted', price:480,    img:CDN('MAC-10 | Neon Rider (Field-Tested)')},
  {id:52, name:'AUG | Fleet Flock (Field-Tested)',          weapon:'AUG',         rarity:'restricted', price:982,    img:CDN('AUG | Fleet Flock (Field-Tested)')},
  {id:53, name:'AWP | Fever Dream (Field-Tested)',          weapon:'AWP',         rarity:'restricted', price:1200,   img:CDN('AWP | Fever Dream (Field-Tested)')},
  {id:54, name:'AK-47 | Safety Net (Field-Tested)',         weapon:'AK-47',       rarity:'restricted', price:242,    img:CDN('AK-47 | Safety Net (Field-Tested)')},
  {id:55, name:'AWP | Atheris (Field-Tested)',              weapon:'AWP',         rarity:'restricted', price:374,    img:CDN('AWP | Atheris (Field-Tested)')},
  {id:56, name:'Desert Eagle | Conspiracy (Field-Tested)',  weapon:'Desert Eagle',rarity:'restricted', price:1409,   img:CDN('Desert Eagle | Conspiracy (Field-Tested)')},
  {id:57, name:'AK-47 | Aquamarine Revenge (Field-Tested)', weapon:'AK-47',       rarity:'covert',     price:4028,   img:CDN('AK-47 | Aquamarine Revenge (Field-Tested)')},
  {id:58, name:'AK-47 | Phantom Disruptor (Field-Tested)',  weapon:'AK-47',       rarity:'restricted', price:668,    img:CDN('AK-47 | Phantom Disruptor (Field-Tested)')},
  {id:59, name:'AWP | Duality (Field-Tested)',              weapon:'AWP',         rarity:'restricted', price:324,    img:CDN('AWP | Duality (Field-Tested)')},
  {id:60, name:'AUG | Syd Mead (Field-Tested)',             weapon:'AUG',         rarity:'restricted', price:922,    img:CDN('AUG | Syd Mead (Field-Tested)')},
  {id:61, name:'Desert Eagle | Heirloom (Field-Tested)',    weapon:'Desert Eagle',rarity:'restricted', price:437,    img:CDN('Desert Eagle | Heirloom (Field-Tested)')},
  {id:62, name:'AK-47 | Point Disarray (Field-Tested)',     weapon:'AK-47',       rarity:'restricted', price:1227,   img:CDN('AK-47 | Point Disarray (Field-Tested)')},
  {id:63, name:'USP-S | Jawbreaker (Battle-Scarred)',       weapon:'USP-S',       rarity:'restricted', price:330,    img:CDN('USP-S | Jawbreaker (Battle-Scarred)')},
  {id:64, name:'AWP | Sun in Leo (Field-Tested)',           weapon:'AWP',         rarity:'restricted', price:1886,   img:CDN('AWP | Sun in Leo (Field-Tested)')},
  {id:65, name:'CZ75-Auto | Yellow Jacket (Field-Tested)',  weapon:'CZ75-Auto',   rarity:'mil',        price:388,    img:CDN('CZ75-Auto | Yellow Jacket (Field-Tested)')},
  {id:66, name:'AK-47 | Searing Rage (Field-Tested)',       weapon:'AK-47',       rarity:'mil',        price:400,    img:CDN('AK-47 | Searing Rage (Field-Tested)')},
  {id:67, name:'AK-47 | Slate (Field-Tested)',              weapon:'AK-47',       rarity:'mil',        price:383,    img:CDN('AK-47 | Slate (Field-Tested)')},
  {id:68, name:'AK-47 | Crossfade (Field-Tested)',          weapon:'AK-47',       rarity:'mil',        price:177,    img:CDN('AK-47 | Crossfade (Field-Tested)')},
  {id:69, name:'AWP | Mortis (Field-Tested)',               weapon:'AWP',         rarity:'mil',        price:327,    img:CDN('AWP | Mortis (Field-Tested)')},
  {id:70, name:'AWP | Worm God (Field-Tested)',             weapon:'AWP',         rarity:'mil',        price:250,    img:CDN('AWP | Worm God (Field-Tested)')},
  {id:71, name:'AUG | Torque (Field-Tested)',               weapon:'AUG',         rarity:'mil',        price:499,    img:CDN('AUG | Torque (Field-Tested)')},
  {id:72, name:'Desert Eagle | Sputnik (Field-Tested)',     weapon:'Desert Eagle',rarity:'mil',        price:175,    img:CDN('Desert Eagle | Sputnik (Field-Tested)')},
  {id:73, name:'AK-47 | Ice Coaled (Field-Tested)',         weapon:'AK-47',       rarity:'mil',        price:445,    img:CDN('AK-47 | Ice Coaled (Field-Tested)')},
  {id:74, name:'AWP | Capillary (Field-Tested)',            weapon:'AWP',         rarity:'mil',        price:47,     img:CDN('AWP | Capillary (Field-Tested)')},
  {id:75, name:'AK-47 | Rat Rod (Field-Tested)',            weapon:'AK-47',       rarity:'mil',        price:396,    img:CDN('AK-47 | Rat Rod (Field-Tested)')},
  {id:76, name:'AUG | Momentum (Field-Tested)',             weapon:'AUG',         rarity:'mil',        price:412,    img:CDN('AUG | Momentum (Field-Tested)')},
  {id:77, name:'AK-47 | Elite Build (Field-Tested)',        weapon:'AK-47',       rarity:'mil',        price:148,    img:CDN('AK-47 | Elite Build (Field-Tested)')},
  {id:78, name:'AWP | Exoskeleton (Field-Tested)',          weapon:'AWP',         rarity:'mil',        price:443,    img:CDN('AWP | Exoskeleton (Field-Tested)')},
  {id:79, name:'AUG | Colony (Field-Tested)',               weapon:'AUG',         rarity:'mil',        price:255,    img:CDN('AUG | Colony (Field-Tested)')},
  {id:80, name:'Desert Eagle | Oxide Blaze (Field-Tested)', weapon:'Desert Eagle',rarity:'mil',        price:42,     img:CDN('Desert Eagle | Oxide Blaze (Field-Tested)')},
  {id:81, name:'AK-47 | Olive Polycam (Field-Tested)',      weapon:'AK-47',       rarity:'consumer',   price:9,      img:CDN('AK-47 | Olive Polycam (Field-Tested)')},
  {id:82, name:'AK-47 | Safari Mesh (Field-Tested)',        weapon:'AK-47',       rarity:'consumer',   price:6,      img:CDN('AK-47 | Safari Mesh (Field-Tested)')},
  {id:83, name:'AWP | Safari Mesh (Field-Tested)',          weapon:'AWP',         rarity:'consumer',   price:10,     img:CDN('AWP | Safari Mesh (Field-Tested)')},
  {id:84, name:'AK-47 | Wintergreen (Field-Tested)',        weapon:'AK-47',       rarity:'consumer',   price:141,    img:CDN('AK-47 | Wintergreen (Field-Tested)')},
  {id:85, name:'AK-47 | VariCamo Grey (Field-Tested)',      weapon:'AK-47',       rarity:'consumer',   price:10,     img:CDN('AK-47 | VariCamo Grey (Field-Tested)')},
  {id:86, name:'AUG | Amber Slipstream (Field-Tested)',     weapon:'AUG',         rarity:'consumer',   price:24,     img:CDN('AUG | Amber Slipstream (Field-Tested)')},
  {id:87, name:'AUG | Condemned (Field-Tested)',            weapon:'AUG',         rarity:'consumer',   price:3,      img:CDN('AUG | Condemned (Field-Tested)')},
  {id:88, name:'CZ75-Auto | Tuxedo (Field-Tested)',         weapon:'CZ75-Auto',   rarity:'consumer',   price:24,     img:CDN('CZ75-Auto | Tuxedo (Field-Tested)')},
  {id:89, name:'CZ75-Auto | Polymer (Field-Tested)',        weapon:'CZ75-Auto',   rarity:'consumer',   price:46,     img:CDN('CZ75-Auto | Polymer (Field-Tested)')},
  {id:90, name:'AK-47 | Steel Delta (Field-Tested)',        weapon:'AK-47',       rarity:'consumer',   price:164,    img:CDN('AK-47 | Steel Delta (Field-Tested)')},
  {id:91, name:'AUG | Luxe Trim (Field-Tested)',            weapon:'AUG',         rarity:'consumer',   price:18,     img:CDN('AUG | Luxe Trim (Field-Tested)')},
  {id:92, name:'AWP | Pit Viper (Field-Tested)',            weapon:'AWP',         rarity:'consumer',   price:45,     img:CDN('AWP | Pit Viper (Field-Tested)')},
  {id:93, name:'AWP | Phobos (Field-Tested)',               weapon:'AWP',         rarity:'consumer',   price:163,    img:CDN('AWP | Phobos (Field-Tested)')},
  {id:94, name:'CZ75-Auto | Circaetus (Field-Tested)',      weapon:'CZ75-Auto',   rarity:'consumer',   price:16,     img:CDN('CZ75-Auto | Circaetus (Field-Tested)')},
  {id:95, name:'AK-47 | Uncharted (Field-Tested)',          weapon:'AK-47',       rarity:'consumer',   price:48,     img:CDN('AK-47 | Uncharted (Field-Tested)')},
  {id:96, name:'AUG | Tom Cat (Field-Tested)',              weapon:'AUG',         rarity:'consumer',   price:17,     img:CDN('AUG | Tom Cat (Field-Tested)')},
  {id:97, name:'AUG | Snake Pit (Field-Tested)',            weapon:'AUG',         rarity:'consumer',   price:2,      img:CDN('AUG | Snake Pit (Field-Tested)')},
  {id:98, name:'AK-47 | Crossfade (Battle-Scarred)',        weapon:'AK-47',       rarity:'consumer',   price:171,    img:CDN('AK-47 | Crossfade (Battle-Scarred)')},
  {id:99, name:'Desert Eagle | Oxide Blaze (Factory New)',  weapon:'Desert Eagle',rarity:'consumer',   price:71,     img:CDN('Desert Eagle | Oxide Blaze (Factory New)')},
  {id:100,name:'AUG | Stymphalian (Battle-Scarred)',        weapon:'AUG',         rarity:'consumer',   price:284,    img:CDN('AUG | Stymphalian (Battle-Scarred)')},
];

const CASES = [
  {id:'starter',  name:'Стартовый кейс',    color:'#4a90d9', badge:null,      price:99,
   items:[33,34,46,54,55,58,59,61,63,65,67,68,69,70,72,74,77,79,80,81,82,83,85,87,88,91,94,96,97]},
  {id:'fracture', name:'Излом',             color:'#d35400', badge:null,      price:149,
   items:[54,55,59,63,65,67,68,70,72,74,77,79,80,81,82,83,85,86,87,88,89,90,91,92,93,94,95,96,97,100]},
  {id:'chroma3',  name:'Хромá 3',           color:'#16a085', badge:null,      price:179,
   items:[8,22,26,35,40,33,43,44,45,46,49,50,51,54,58,59,61,63,65,67,68,70,72,74,75,80,82,84,86,88,89,90,91,92,93,99]},
  {id:'prisma',   name:'Кейс «Призма»',     color:'#8e44ad', badge:null,      price:199,
   items:[22,25,35,30,33,43,44,45,46,47,49,50,51,52,54,58,59,60,63,65,66,67,69,70,71,73,75,78,84,86,89,90,92,93,95,98,99]},
  {id:'spectrum2',name:'Спектр 2',          color:'#c0392b', badge:null,      price:229,
   items:[9,13,17,21,25,26,29,32,37,48,30,34,36,42,43,46,47,52,53,54,55,59,60,62,63,65,66,67,71,73,76,77,78,79,83,85,87,89,94,95,96,98]},
  {id:'gamma',    name:'Гамма-2',           color:'#27ae60', badge:null,      price:249,
   items:[8,9,17,22,25,26,31,37,48,30,33,34,36,41,42,46,47,54,55,59,61,62,64,66,67,68,69,70,74,76,77,83,84,86,90,91,92,93,98]},
  {id:'recoil',   name:'Кейс «Отдача»',     color:'#e91e63', badge:'ХИТ',    price:299,
   items:[3,4,9,13,17,21,24,25,26,29,32,38,39,40,48,57,41,46,47,51,52,53,56,60,64,65,66,69,71,72,73,76,78,80,82,83,85,89,90,94,95,99]},
  {id:'hydra',    name:'Операция «Гидра»',  color:'#1abc9c', badge:null,      price:329,
   items:[3,4,9,10,12,13,17,18,21,22,24,26,31,32,35,37,38,48,57,30,36,41,43,14,47,53,55,56,59,60,62,63,64,65,66,69,70,71,73,74,75,76,83,84,92,93,95]},
  {id:'clutch',   name:'Кейс «Блеск»',      color:'#f39c12', badge:'ГОРЯЧИЙ',price:349,
   items:[1,3,4,5,7,13,18,19,20,21,22,24,25,27,28,29,31,32,38,39,48,57,30,41,42,14,46,47,50,52,53,56,60,61,62,64,65,66,69,71,72,73,75,79,84,86,90,92,93,98,99]},
  {id:'danger',   name:'Опасная зона',       color:'#e8a020', badge:'ТОП',    price:399,
   items:[3,4,5,8,9,10,12,13,15,18,19,20,21,23,24,27,28,29,31,32,35,38,39,48,57,36,14,46,47,49,50,52,53,56,60,61,62,64,65,66,69,71,73,75,76,78]},
  {id:'dreams',   name:'Мечты и кошмары',   color:'#9b59b6', badge:null,      price:449,
   items:[1,2,3,4,5,6,7,11,12,13,15,16,18,19,20,22,23,24,25,27,28,29,31,32,38,39,40,48,57,41,14,47,52,53,56,64,65,66,69,71,73,78]},
  {id:'cs20',     name:'CS20 Кейс',         color:'#8e44ad', badge:'ЛИМИТ',  price:549,
   items:[1,2,3,4,5,6,7,10,11,12,13,15,16,18,19,20,22,23,24,25,26,27,28,29,31,32,35,38,39,40,48,57,36,41,14,47,52,53,56,60,62,64,65,66,69,71,73,76,78]},
  {id:'free',     name:'Ежедневный кейс',   color:'#27ae60', badge:'FREE',    price:0,
   items:[46,54,55,65,67,68,69,70,72,74,77,79,80,81,82,83,85,86,87,88,89,90,91,92,93,94,95,96,97,98,99,100]},
];

const SKIN_MAP = new Map(SKINS.map(s => [s.id, s]));
const CASE_MAP = new Map(CASES.map(c => [c.id, c]));

module.exports = { SKINS, CASES, SKIN_MAP, CASE_MAP };
